# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Reference callable billing-support agent for the govern-and-remeasure loop.

``agent`` is the ungoverned baseline (the identity-verification gate lives only
in the system prompt). ``agent_guarded`` is the same agent re-run with the ACS
policy generated by ``assert-ai acs generate`` wrapping the high-risk tools, so
ASSERT can measure the failure-rate delta between the two.
"""
